In [2]:
import myfunc as mf

In [13]:
b = mf.myfunc(3,4)
id(b)

1833987328

In [10]:
a = eval('mf.myfunc(3,4)')
id(a)

1833987328

In [14]:
import re

In [50]:
str = "The rain in Spainxfjf falls mainly in the plain!"

#Check if the string contains "a" followed by exactly two "l" characters:
y = re.findall("nxx*", str)
x = re.findall("al{2}", str)

In [51]:
print(x);print(y)

['all']
['nx']

In [52]:
str = "The rain in Spain"

#Check if "ain" is present at the beginning of a WORD:

x = re.findall(r"\bain", str)

print(x)

[]

In [59]:
a = [1,2,3,4]
b = a
print(b)
b.append(9)

[1, 2, 3, 4]

In [60]:
b = [6,7]

In [61]:
print(a)

[1, 2, 3, 4, 9]

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a = [1,2,3,4,5,6,7,8]

In [5]:
a[1:]

[2, 3, 4, 5, 6, 7, 8]

In [7]:
a[:-1]

[1, 2, 3, 4, 5, 6, 7]

In [8]:
a[1:]

[2, 3, 4, 5, 6, 7, 8]

In [10]:
a[1:-1]

[2, 3, 4, 5, 6, 7]

In [11]:
a[::-1]

[8, 7, 6, 5, 4, 3, 2, 1]

In [12]:
a[:-1]

[1, 2, 3, 4, 5, 6, 7]

In [13]:
a[-2]

7

In [2]:
import datetime

In [4]:
x = datetime.datetime.now()

In [22]:
x.strftime("%S") == "57"

True

In [20]:
print(x)

2019-04-02 09:25:57.846534

In [23]:
import time

In [3]:
dta = pd.read_excel("USDBRL_PriceHist.xlsx", index_col=0)

In [27]:
time.strftime("%Y,%m,%d,%H,%M,%S")

'2019,04,02,09,47,48'

In [4]:
dta.index[0].hour

13

In [5]:
start_time = "2018/05/15"

In [22]:
start_time = datetime.datetime(2018, 5, 21)

In [20]:
end_time = datetime.datetime(2018, 5, 21, 13,1)

In [21]:
start_time<= end_time

True

In [32]:
Dates = dta.index

In [56]:
selected = dta[np.logical_and(Dates.month == start_time.month, Dates.day == start_time.day)]

In [57]:
selected

,Close,USDBRL_Future,1W Maturity,1M Maturity,3M Maturity,V1W,V1M,V3M
Dates,,,,,,,,
2018-05-21 13:01:00,3.7060,3.7095,0.0,0.055743,0.222410,0.158400,0.14782,0.14177
2018-05-21 13:02:00,3.7121,3.7155,0.0,0.055740,0.222407,0.158400,0.14782,0.14177
2018-05-21 13:03:00,3.7151,3.7180,0.0,0.055737,0.222404,0.158400,0.14782,0.14177
2018-05-21 13:04:00,3.7143,3.7175,0.0,0.055735,0.222401,0.156650,0.14747,0.14157
2018-05-21 13:05:00,3.7172,3.7205,0.0,0.055732,0.222399,0.156650,0.14747,0.14157
2018-05-21 13:06:00,3.7192,3.7220,0.0,0.055729,0.222396,0.153825,0.14730,0.14160
2018-05-21 13:07:00,3.7235,3.7270,0.0,0.055726,0.222393,0.153825,0.14730,0.14160
2018-05-21 13:08:00,3.7221,3.7245,0.0,0.055724,0.222390,0.153825,0.14730,0.14160
2018-05-21 13:09:00,3.7218,3.7250,0.0,0.055721,0.222388,0.153825,0.14730,0.14155
2018-05-21 13:10:00,3.7221,3.7255,0.0,0.055718,0.222385,0.153825,0.14730,0.14155
2018-05-21 13:11:00,3.7203,3.7235,0.0,0.055715,0.222382,0.153775,0.14730,0.14155
2018-05-21 13:12:00,3.7210,3.7250,0.0,0.055713,0.222379,0.153775,0.14730,0.14155
2018-05-21 13:13:00,3.7187,3.7215,0.0,0.055710,0.222377,0.153775,0.14730,0.14155
2018-05-21 13:14:00,3.7167,3.7195,0.0,0.055707,0.222374,0.153775,0.14730,0.14155
2018-05-21 13:15:00,3.7128,3.7155,0.0,0.055704,0.222371,0.153775,0.14730,0.14155
2018-05-21 13:16:00,3.7123,3.7155,0.0,0.055702,0.222368,0.156125,0.14865,0.14185
2018-05-21 13:17:00,3.7122,3.7155,0.0,0.055699,0.222366,0.156125,0.14865,0.14185
2018-05-21 13:18:00,3.7153,3.7190,0.0,0.055696,0.222363,0.154375,0.14795,0.14145
2018-05-21 13:19:00,3.7163,3.7190,0.0,0.055693,0.222360,0.154375,0.14795,0.14145
2018-05-21 13:20:00,3.7158,3.7190,0.0,0.055691,0.222357,0.154475,0.14795,0.14132
2018-05-21 13:21:00,3.7150,3.7180,0.0,0.055688,0.222354,0.154375,0.14795,0.14148
2018-05-21 13:22:00,3.7112,3.7145,0.0,0.055685,0.222352,0.154375,0.14795,0.14148
2018-05-21 13:23:00,3.7112,3.7145,0.0,0.055682,0.222349,0.154375,0.14795,0.14148
2018-05-21 13:24:00,3.7141,3.7175,0.0,0.055680,0.222346,0.154375,0.14795,0.14148
2018-05-21 13:25:00,3.7137,3.7170,0.0,0.055677,0.222343,0.154375,0.14795,0.14148
2018-05-21 13:26:00,3.7137,3.7165,0.0,0.055674,0.222341,0.154375,0.14795,0.14148
2018-05-21 13:27:00,3.7132,3.7165,0.0,0.055671,0.222338,0.154375,0.14795,0.14148
2018-05-21 13:28:00,3.7127,3.7160,0.0,0.055669,0.222335,0.154375,0.14795,0.14148
2018-05-21 13:29:00,3.7129,3.7155,0.0,0.055666,0.222332,0.154375,0.14795,0.14148
2018-05-21 13:30:00,3.7115,3.7150,0.0,0.055663,0.222330,0.154425,0.14770,0.14135
...,...,...,...,...,...,...,...,...
2018-05-21 21:30:00,3.6791,3.6820,0.0,0.054351,0.221018,0.144000,0.14300,0.13962
2018-05-21 21:31:00,3.6778,3.6810,0.0,0.054349,0.221015,0.144000,0.14300,0.13962
2018-05-21 21:32:00,3.6778,3.6805,0.0,0.054346,0.221012,0.144000,0.14300,0.13962
2018-05-21 21:33:00,3.6788,3.6815,0.0,0.054343,0.221010,0.144000,0.14300,0.13962
2018-05-21 21:34:00,3.6803,3.6830,0.0,0.054340,0.221007,0.144000,0.14300,0.13962
2018-05-21 21:35:00,3.6797,3.6825,0.0,0.054338,0.221004,0.143600,0.14300,0.13960
2018-05-21 21:36:00,3.6803,3.6830,0.0,0.054335,0.221001,0.143600,0.14300,0.13960
2018-05-21 21:37:00,3.6797,3.6830,0.0,0.054332,0.220999,0.143600,0.14300,0.13960
2018-05-21 21:38:00,3.6797,3.6825,0.0,0.054329,0.220996,0.143600,0.14300,0.13960
2018-05-21 21:39:00,3.6797,3.6825,0.0,0.054326,0.220993,0.143600,0.14300,0.13960
2018-05-21 21:40:00,3.6788,3.6820,0.0,0.054324,0.220990,0.143550,0.14300,0.13960
2018-05-21 21:41:00,3.6788,3.6815,0.0,0.054321,0.220988,0.143550,0.14300,0.13960
2018-05-21 21:42:00,3.6778,3.6810,0.0,0.054318,0.220985,0.143550,0.14300,0.13960
2018-05-21 21:43:00,3.6767,3.6800,0.0,0.054315,0.220982,0.143550,0.14300,0.13960
2018-05-21 21:44:00,3.6758,3.6785,0.0,0.054313,0.220979,0.143550,0.14300,0.13960
2018-05-21 21:45:00,3.6758,3.6790,0.0,0.054310,0.220977,0.142550,0.14313,0.13962
2018-05-21 21:46:00,3.6758,3.6790,0.0,0.054307,0.220974,0.142550,0.14313,0.13962
2018-05-21 21:47:00,3.6768,3.6795,0.0,0.054304,0.220971,0.142550,0.14313,0.13962
2018-05-21 21:48:00,3.6760,3.6795,0.0,0.054302,0.220968,0.142550,0.14313,0.13962
2018-05-21 21:49:00,3.6772,3.6800,0.0,0.054299,0.220966,0.142550,0.14313,0.13962
2018-05-21 21:50:00,3.6775,3.6800,0.0,0.054296,0.220963,0.142525,0.14313,0.13962
2018-05-21 21:51:00,3.6772,3.6800,0.0,0.054293,0.220960,0.142525,0.14313,0.13962
2018-05-21 21:52:00,3.6768,3.6795,0.0,0.054291,0.220957,0.142500,0.14313,0.13960
2018-05-21 21:53:00,3.6768,3.6800,0.0,0.054288,0.220955,0.142500,0.14313,0.13960
2018-05-21 21:54:00,3.6762,3.6790,0.0,0.054285,0.220952,0.142500,0.14313,0.13960
2018-05-21 21:55:00,3.6743,3.6770,0.0,0.054282,0.220949,0.143475,0.14313,0.13960
2018-05-21 21:56:00,3.6753,3.6790,0.0,0.054280,0.220946,0.143475,0.14313,0.13960
2018-05-21 21:57:00,3.6750,3.6775,0.0,0.054277,0.220944,0.143475,0.14313,0.13960
2018-05-21 21:58:00,3.6762,3.6795,0.0,0.054274,0.220941,0.143475,0.14313,0.13960
2018-05-21 21:59:00,3.6778,3.6805,0.0,0.054271,0.220938,0.143475,0.14313,0.13960

In [52]:
a or b

[True, False]

In [132]:

def dailydata_selector(dta, dates, start_date):
    return dta[np.logical_and(dates.month == start_date.month, dates.day == start_date.day)]

def option_price(s, tau, k, sigma, r, q):
    d1 = (np.log(s/k) + (r - q + sigma**2/2)*tau)/(sigma*tau)
    d2 = d1 - sigma*np.sqrt(tau)
    return s*np.exp(-q*tau)*norm.cdf(d1) - k * np.exp(-r*tau)*norm.cdf(d2)


def delta(s, tau, k, sigma, r, q):
    d1 = (np.log(s/k) + (r - q + sigma**2/2)*tau)/(sigma*tau)
    return np.exp(-q*tau) * norm.cdf(d1)


def hedging_pnl(s, tau, sigma,k, r, q):

    optionPV = option_price(s[:-1],tau[:-1],k,sigma[:-1],r,q)
    repl_port = np.zeros((len(tau), 1))
    total_port = np.zeros((len(tau), 1))
    bankacc = np.zeros((len(tau), 1))
    delta_vec = delta(s[:-1], tau[:-1], k, sigma[:-1], r, q)

    stock_pos = delta_vec[1:] * s[1:-1]
    stock_pos_diff = stock_pos - delta_vec[:-1] * s[1:-1]
    bankacc[0] = optionPV[0] - delta_vec[0]*s[0]
    repl_port[0] = optionPV[0]
    dt = np.diff(tau)

    for t in range(len(dt)-1):
        bankacc[t+1] = bankacc[t]*(1 + dt[t]*r) - stock_pos_diff[t] *(1-dt[t]*q)
        repl_port[t+1] = stock_pos[t] + bankacc[t+1]
        total_port[t+1] = optionPV[t+1] - repl_port[t+1] - bankacc[0]*(1 + r*dt[0])**tau[t+1]

    optionPV.append(np.max(s[-1] - k, 0))
    bankacc[-1] = bankacc[-2]*(1+dt[-1]*r)
    repl_port[-1] = delta_vec[-1]*s[-1] + bankacc[-1]
    total_port[-1] = optionPV[-1] = repl_port[-1] - bankacc[0]* (1+ r*dt[0])**tau[-1]

    return optionPV, repl_port, total_port

In [127]:
def duration_data_selector(dta, duration):

    if duration == "1M":
        new_dta = dta[dta["1M Maturity"]>0]
        return new_dta["Close"].values, new_dta["1M Maturity"].values, new_dta["V1M"].values
    elif duration == "3M":
        new_dta = dta[dta["3M Maturity"]>0]
        return new_dta["Close"].values, new_dta["3M Maturity"].values, new_dta["V3M"].values
    elif duration == "1W":
        new_dta = dta[dta["1W Maturity"]>0]
        return new_dta["Close"].values, new_dta["1W Maturity"].values, new_dta["V1W"].values

In [151]:
s, tau, sigma = duration_data_selector(dta, "1M")
from scipy.stats import norm

numpy.ndarray

In [135]:
op = hedging_pnl( s, tau, sigma, s[0],  0.065, 0.02)

C:\Users\canze\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide

C:\Users\canze\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in true_divide
  if sys.path[0] == '':

AttributeError: 'numpy.ndarray' object has no attribute 'append'

array([[1.        , 3.5832    , 3.5787    , ..., 3.        , 2.        ,
        1.        ],
       [3.588     , 3.59      , 3.586     , ..., 3.6955    , 3.6965    ,
        3.696     ],
       [0.01984127, 0.01983851, 0.01983576, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.1394    , 0.1394    , 0.1394    , ..., 0.1994    , 0.1994    ,
        0.199425  ],
       [0.1268    , 0.1268    , 0.1268    , ..., 0.1757    , 0.1757    ,
        0.1752    ],
       [0.12865   , 0.12865   , 0.12865   , ..., 0.16362   , 0.16362   ,
        0.16362   ]])

In [120]:
arr = dta2.T.values[0]

In [122]:
arr = arr[0:5]

In [123]:
arr2 = np.ones((5,1))

In [126]:
arr*arr2

array([[1.    , 3.5832, 3.5787, 3.5782, 3.5789],
       [1.    , 3.5832, 3.5787, 3.5782, 3.5789],
       [1.    , 3.5832, 3.5787, 3.5782, 3.5789],
       [1.    , 3.5832, 3.5787, 3.5782, 3.5789],
       [1.    , 3.5832, 3.5787, 3.5782, 3.5789]])